import React from 'react'
import { Download, FileText, File, Loader2, AlertCircle } from 'lucide-react'
import { Skeleton } from '@/components/ui/skeleton'
import { Badge } from '@/components/ui/badge'
import { formatDate, truncate } from '@/lib/utils'
import type { GeneratedReport } from '@/types'

interface GeneratedReportsListProps {
  reports: GeneratedReport[]
  isLoading?: boolean
  error?: Error | null
}

function formatBadgeVariant(format: string | undefined) {
  switch (format) {
    case 'PDF': return 'destructive'
    case 'CSV': return 'success'
    case 'Excel': return 'info'
    default: return 'secondary'
  }
}

function FormatIcon({ format }: { format?: string }) {
  if (format === 'PDF') return <FileText className="h-4 w-4" style={{ color: '#ef4444' }} />
  if (format === 'CSV') return <File className="h-4 w-4" style={{ color: '#22c55e' }} />
  return <File className="h-4 w-4" style={{ color: 'var(--color-mercury-blue)' }} />
}

export function GeneratedReportsList({ reports, isLoading = false, error }: GeneratedReportsListProps) {
  return (
    <div
      style={{
        backgroundColor: 'var(--color-midnight-slate)',
        border: '1px solid rgba(112, 112, 125, 0.15)',
      }}
    >
      {/* Header */}
      <div
        className="flex items-center justify-between px-6 py-4"
        style={{ borderBottom: '1px solid rgba(112, 112, 125, 0.15)' }}
      >
        <h2 className="text-base font-medium" style={{ color: 'var(--color-starlight)' }}>
          Generated Reports
        </h2>
        <span className="text-xs px-2 py-1" style={{
          backgroundColor: 'rgba(82, 102, 235, 0.15)',
          color: 'var(--color-mercury-blue)',
          borderRadius: '32px',
        }}>
          {reports.length} report{reports.length !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr style={{ backgroundColor: 'var(--color-graphite)' }}>
              {['Report Name', 'Type', 'Date Range', 'Generated By', 'Format', 'File Size', 'Date', ''].map((h) => (
                <th
                  key={h}
                  className="px-4 py-3 text-left text-xs uppercase tracking-wider"
                  style={{ color: 'var(--color-silver)' }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              Array.from({ length: 4 }).map((_, i) => (
                <tr key={`skel-${i}`} style={{ borderBottom: '1px solid rgba(112, 112, 125, 0.12)' }}>
                  {Array.from({ length: 8 }).map((__, j) => (
                    <td key={j} className="px-4 py-3">
                      <Skeleton className="h-4 w-full" style={{ backgroundColor: 'var(--color-graphite)' }} />
                    </td>
                  ))}
                </tr>
              ))
            ) : error ? (
              <tr>
                <td colSpan={8} className="px-6 py-10 text-center">
                  <div className="flex flex-col items-center gap-2">
                    <AlertCircle className="h-6 w-6" style={{ color: '#ef4444' }} />
                    <p className="text-sm" style={{ color: 'var(--color-silver)' }}>Failed to load reports</p>
                  </div>
                </td>
              </tr>
            ) : reports.length === 0 ? (
              <tr>
                <td colSpan={8} className="px-6 py-12 text-center">
                  <div className="flex flex-col items-center gap-3">
                    <div
                      className="flex items-center justify-center w-12 h-12"
                      style={{ backgroundColor: 'rgba(82, 102, 235, 0.1)', borderRadius: '6px' }}
                    >
                      <FileText className="h-6 w-6" style={{ color: 'var(--color-mercury-blue)' }} />
                    </div>
                    <p className="text-sm" style={{ color: 'var(--color-silver)' }}>No reports generated yet</p>
                    <p className="text-xs" style={{ color: 'var(--color-lead)' }}>Use the Report Builder above to generate your first report</p>
                  </div>
                </td>
              </tr>
            ) : (
              reports.map((report) => (
                <tr
                  key={report.guid}
                  className="transition-colors duration-150 group"
                  style={{ borderBottom: '1px solid rgba(112, 112, 125, 0.12)' }}
                  onMouseEnter={(e) => (e.currentTarget.style.backgroundColor = 'var(--color-graphite)')}
                  onMouseLeave={(e) => (e.currentTarget.style.backgroundColor = 'transparent')}
                >
                  {/* Report Name */}
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <FormatIcon format={report.format} />
                      <span style={{ color: 'var(--color-starlight)' }}>
                        {truncate(report.report_name ?? '—', 32)}
                      </span>
                    </div>
                  </td>

                  {/* Type */}
                  <td className="px-4 py-3">
                    <span
                      className="text-xs px-2 py-1"
                      style={{
                        backgroundColor: 'rgba(82, 102, 235, 0.12)',
                        color: 'var(--color-mercury-blue)',
                        borderRadius: '32px',
                      }}
                    >
                      {report.report_type ?? '—'}
                    </span>
                  </td>

                  {/* Date Range */}
                  <td className="px-4 py-3 text-xs" style={{ color: 'var(--color-silver)' }}>
                    {report.date_range_start && report.date_range_end
                      ? `${formatDate(report.date_range_start)} – ${formatDate(report.date_range_end)}`
                      : '—'}
                  </td>

                  {/* Generated By */}
                  <td className="px-4 py-3" style={{ color: 'var(--color-silver)' }}>
                    {report.generated_by ?? '—'}
                  </td>

                  {/* Format */}
                  <td className="px-4 py-3">
                    <Badge variant={formatBadgeVariant(report.format) as 'destructive' | 'success' | 'info' | 'secondary'}>
                      {report.format ?? '—'}
                    </Badge>
                  </td>

                  {/* File Size */}
                  <td className="px-4 py-3 text-xs" style={{ color: 'var(--color-silver)' }}>
                    {report.file_size ?? '—'}
                  </td>

                  {/* Date */}
                  <td className="px-4 py-3 text-xs" style={{ color: 'var(--color-silver)' }}>
                    {formatDate(report.generated_at ?? report.created_at)}
                  </td>

                  {/* Download */}
                  <td className="px-4 py-3">
                    <button
                      type="button"
                      className="flex items-center justify-center w-8 h-8 transition-all duration-150 opacity-0 group-hover:opacity-100"
                      style={{
                        backgroundColor: 'rgba(82, 102, 235, 0.15)',
                        color: 'var(--color-mercury-blue)',
                        borderRadius: '6px',
                      }}
                      title="Download report"
                    >
                      <Download className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
